### ISSUE TITLE
Connection refused exception

### ISSUE THREAD

**Issue by SamRaeburn** [TonyTewsAngels/Dev#134]
ertain cirumstances (I haven't been able to work out what they are) the following exception is thrown "Connection refused: connect".

Looks to be something to do with using online sources.

**Comment by ajewers** [comment]
Source of bug has been narrowed down; Related to some use of CSS stylesheets by the controls of the video and audio handlers. Could not be replicated on my machine or by wave media. 

For the video handler the bug occurs when the mouse first enters the video area, triggering the display of the controls. No line number is shown in the exception, but the text suggests the client is attempting to retrieve some CSS stylesheet information from an online source, but cannot connect.

@SamRaeburn could you please replicate the bug and post here the exact text of the exception thrown?

**Comment by SamRaeburn** [comment]
![Connection Refused Error](//userfs/sr896/w2k/Electronic Engineering/3rd/SWEng/connection refused error.png)

**Comment by SamRaeburn** [comment]
``` c
java.net.ConnectException: Connection refused: connect
java.net.ConnectException: Connection refused: connect
    at java.net.DualStackPlainSocketImpl.connect0(Native Method)
    at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
    at java.net.PlainSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at sun.net.ftp.impl.FtpClient.doConnect(Unknown Source)
    at sun.net.ftp.impl.FtpClient.tryConnect(Unknown Source)
    at sun.net.ftp.impl.FtpClient.connect(Unknown Source)
    at sun.net.ftp.impl.FtpClient.connect(Unknown Source)
    at sun.net.www.protocol.ftp.FtpURLConnection.connect(Unknown Source)
    at sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(Unknown Source)
    at java.net.URL.openStream(Unknown Source)
    at com.sun.javafx.css.Stylesheet.loadBinary(Unknown Source)
    at com.sun.javafx.css.StyleManager.loadStylesheetUnPrivileged(Unknown Source)
    at com.sun.javafx.css.StyleManager.loadStylesheet(Unknown Source)
    at com.sun.javafx.css.StyleManager.access$1900(Unknown Source)
    at com.sun.javafx.css.StyleManager$StylesheetContainer.gatherParentStylesheets(Unknown Source)
    at com.sun.javafx.css.StyleManager$StylesheetContainer.getStyleHelper(Unknown Source)
    at com.sun.javafx.css.StyleManager$StylesheetContainer.access$1300(Unknown Source)
    at com.sun.javafx.css.StyleManager.getStyleHelper(Unknown Source)
    at javafx.scene.Node.impl_createStyleHelper(Unknown Source)
    at javafx.scene.Node.impl_processCSS(Unknown Source)
    at javafx.scene.Parent.impl_processCSS(Unknown Source)
    at javafx.scene.control.Control.impl_processCSS(Unknown Source)
    at javafx.scene.Parent.impl_processCSS(Unknown Source)
    at javafx.scene.Node.processCSS(Unknown Source)
    at javafx.scene.Node.processCSS(Unknown Source)
    at javafx.scene.Node.processCSS(Unknown Source)
    at javafx.scene.Node.processCSS(Unknown Source)
    at javafx.scene.Node.processCSS(Unknown Source)
    at javafx.scene.Scene.doCSSPass(Unknown Source)
    at javafx.scene.Scene.access$3800(Unknown Source)
    at javafx.scene.Scene$ScenePulseListener.pulse(Unknown Source)
    at com.sun.javafx.tk.Toolkit$5.run(Unknown Source)
    at com.sun.javafx.tk.Toolkit$5.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.Toolkit.runPulse(Unknown Source)
    at com.sun.javafx.tk.Toolkit.firePulse(Unknown Source)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
    at com.sun.javafx.tk.quantum.QuantumToolkit$9.run(Unknown Source)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.access$100(Unknown Source)
    at com.sun.glass.ui.win.WinApplication$3$1.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Exception in thread "JavaFX Application Thread" 
```

**Comment by SamRaeburn** [comment]
![connection refused error](https://cloud.githubusercontent.com/assets/10668587/7799844/a4e94940-0303-11e5-8243-f329dcbbd82e.png)
