### ISSUE TITLE
Text Handler Heap Space Error

### ISSUE THREAD

**Issue by ajewers** [TonyTewsAngels/Dev#208]
Error Text:

``` c
java.lang.OutOfMemoryError: Java heap space
    at java.nio.HeapByteBuffer.<init>(Unknown Source)
    at java.nio.ByteBuffer.allocate(Unknown Source)
    at sun.nio.cs.StreamEncoder.<init>(Unknown Source)
    at sun.nio.cs.StreamEncoder.<init>(Unknown Source)
    at sun.nio.cs.StreamEncoder.forOutputStreamWriter(Unknown Source)
    at java.io.OutputStreamWriter.<init>(Unknown Source)
    at java.io.PrintStream.<init>(Unknown Source)
    at java.io.PrintStream.<init>(Unknown Source)
    at java.io.PrintStream.<init>(Unknown Source)
    at sun.misc.CharacterEncoder.encodeBufferPrefix(Unknown Source)
    at sun.misc.CharacterEncoder.encodeBuffer(Unknown Source)
    at javafx.scene.web.WebEngine$3.invalidated(Unknown Source)
    at javafx.beans.property.StringPropertyBase.markInvalid(Unknown Source)
    at javafx.beans.property.StringPropertyBase.set(Unknown Source)
    at javafx.beans.property.StringPropertyBase.set(Unknown Source)
    at javafx.scene.web.WebEngine.setUserStyleSheetLocation(Unknown Source)
    at wavemedia.text.Text.drawBuffer(Text.java:163)
    at wavemedia.text.Text.drawText(Text.java:81)
    at wavemedia.text.TextHandler.createTextbox(TextHandler.java:47)
    at teacheasy.render.Renderer.renderText(Renderer.java:154)
    at teacheasy.render.Renderer.renderPage(Renderer.java:76)
    at teacheasy.runtime.EditorRunTimeData.redraw(EditorRunTimeData.java:501)
    at teacheasy.runtime.editor.PropertiesPane.redraw(PropertiesPane.java:223)
    at teacheasy.runtime.editor.GraphicPropertiesController$ColorPropertyChangedHandler.handle(GraphicPropertiesController.java:241)
    at teacheasy.runtime.editor.GraphicPropertiesController$ColorPropertyChangedHandler.handle(GraphicPropertiesController.java:1)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
    at com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
```

**Comment by ajewers** [comment]
Same as #215, not text handler related.
